version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000
    volumes:
      - ./auth_info_v4:/app/auth_info_v4
      - ./settings.json:/app/settings.json
