@echo off
echo [CodeXcel] Stopping any existing process on port 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3000') do taskkill /F /PID %%a 2>nul
echo [CodeXcel] Installing dependencies...
call npm install
echo [CodeXcel] Starting server...
node server.js
pause
